name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi 😄, thanks for creating your first issue at RESCUE, do read and follow the [Code of Conduct](https://github.com/swapnilsparsh/Rescue/blob/master/Code_of_Conduct.md) and the [Contribution Guidelines](https://github.com/swapnilsparsh/Rescue/blob/master/Contributing.md) while contributing. 🚀'
        pr-message: 'Welcome to the community ! 🙂 Thank you for your pull request . We will  be getting back to you soon 🚀. Your patience will be greatly appreciated!Thanks! 🙂'